# Use a imagem do Node.js
FROM node:18-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos do package.json e package-lock.json
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia todos os arquivos para o container
COPY . .

# Expõe a porta 5173
EXPOSE 5173

# Comando para iniciar o servidor
CMD ["npm", "run", "dev", "--", "--host"]
